-- ---------------------------------------------------------------------------
-- 0001_init.sql
--
-- Creates the `tasks` table.
--
-- Schema version control is part of configuration management: the database
-- shape is an artefact that changes over time, so its changes are recorded as
-- ordered, non-destructive migration files rather than as ad-hoc SQL run by
-- hand. Each file is applied exactly once and the ledger in `schema_migrations`
-- records which ones have run.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tasks (
  -- UUID v4 generated by the application, so an id is known before insert and
  -- two clients creating tasks offline cannot collide.
  id            TEXT    PRIMARY KEY,

  -- Presentation fields.
  title         TEXT    NOT NULL,
  description   TEXT    NOT NULL DEFAULT '',

  -- Constrained enumerations. Enforcing them in the schema as well as in the
  -- validation layer means a bug in the API cannot write an invalid row.
  status        TEXT    NOT NULL DEFAULT 'todo'
                        CHECK (status IN ('todo', 'in_progress', 'blocked', 'done')),
  priority      TEXT    NOT NULL DEFAULT 'medium'
                        CHECK (priority IN ('low', 'medium', 'high', 'urgent')),

  -- ISO-8601 date (YYYY-MM-DD) chosen by the user, or NULL when no due date.
  due_date      TEXT    CHECK (due_date IS NULL OR due_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),

  -- ISO-8601 UTC timestamps. Defaulted by SQLite so a row written by any path
  -- carries a consistent timestamp.
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  completed_at  TEXT,

  -- Optimistic concurrency. Every update increments this value, and a client
  -- that supplies a stale value has its write rejected rather than silently
  -- overwriting a change it never saw.
  version       INTEGER NOT NULL DEFAULT 1,

  -- A completed task must record when it was completed, and an incomplete one
  -- must not. This is the kind of invariant that is cheap to state once here
  -- and expensive to re-check in every code path.
  CHECK ((status = 'done') = (completed_at IS NOT NULL))
);

-- The list endpoint filters on status and orders by due date, so one composite
-- index serves the common query without a full scan.
CREATE INDEX IF NOT EXISTS idx_tasks_status_due_date ON tasks (status, due_date);

-- Supports "most recently updated first", the default ordering when no filter
-- is supplied.
CREATE INDEX IF NOT EXISTS idx_tasks_updated_at ON tasks (updated_at DESC);

-- NOTE ON `updated_at`
-- An AFTER UPDATE trigger that rewrote `updated_at` was considered and
-- rejected. Inside an AFTER UPDATE trigger, `OLD` has already been overwritten
-- by the new row, so the trigger cannot reliably compare the two, and the model
-- layer must set `updated_at` explicitly on every update anyway in order to
-- bump `version` in the same statement. One explicit write is clearer than a
-- trigger that duplicates it.
